[package]
name = "ncm-converter"
version = "1.0.0"
edition = "2021"

[lib]
name = "ncm_converter_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aes = "0.8"
cipher = "0.4"
base64 = "0.22"
id3 = "1"
metaflac = "0.2"
